# Proyecto de Machine Learning
## Predicción del precio de seguros para mascotas

Este proyecto corresponde a la segunda fase del trabajo iniciado con el Análisis Exploratorio de Datos (EDA). Su objetivo es desarrollar un modelo de Machine Learning que permita estimar el precio de nuevas cotizaciones e identificar y cuantificar las variables con mayor influencia en su cálculo.

## Notebook 01 – Preprocesamiento

Este notebook contiene el proceso de revisión, limpieza y preparación del conjunto de datos que será utilizado durante el entrenamiento de los modelos de Machine Learning.

Las transformaciones implementadas seguirán las decisiones definidas en el **Documento 02 – Plan de Preprocesamiento**.

# 1. Importación de librerías

En esta sección se importan las librerías necesarias para realizar la carga, revisión, limpieza y preparación inicial del dataset.

Las dependencias adicionales se incorporarán únicamente cuando sean necesarias durante el desarrollo del preprocesamiento.

In [1]:
import numpy as np
import pandas as pd

# 2. Configuración del entorno

## Objetivo

Configurar el entorno de trabajo para facilitar la visualización de los datos y mantener un formato consistente durante el desarrollo del proyecto.

## Implementación

In [3]:
# Configuración de pandas
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# Configuración de NumPy
np.set_printoptions(suppress=True)

# 3. Carga del dataset

## Objetivo

Cargar el conjunto de datos original que servirá como base para el desarrollo del proyecto de Machine Learning.

Durante esta fase se verificará que la carga se haya realizado correctamente antes de iniciar el proceso de revisión y preprocesamiento.

In [4]:
# Carga del dataset
df = pd.read_csv("../data/matriz_cotizaciones_grupos_original.csv")

# Mostrar las primeras filas
df.head()

,id,grupo_raza,grupo_raza_nombre,pet_species,pet_race_code,pet_race_name,pet_gender,pet_age_nr,pet_sterilized,sterilized_when,is_pure_breed,is_dangerous,owner_postal_code,owner_municipality,plan_code,plan_name,capital_vet_total,capital_vet_plus,capital_rc,precio_mensual,precio_anual,fecha_cotizacion,multisimulation_id,api_response
0,4930,1,Australian Terrier,1,110251,Australian Terrier,M,6,N,NaN,t,f,28001,Madrid,3,PET3,1250.0,1000.0,0.0,19.30,220.40,2026-04-11 09:03:45.882914,595360,NaN
1,4931,1,Australian Terrier,1,110251,Australian Terrier,F,7,S,S2,t,f,28001,Madrid,3,PET3,1250.0,1000.0,0.0,18.53,211.62,2026-04-11 09:03:54.337379,595362,NaN
2,4932,1,Australian Terrier,1,110251,Australian Terrier,F,7,S,S3,t,f,28001,Madrid,3,PET3,1250.0,1000.0,0.0,19.08,217.94,2026-04-11 09:04:01.700459,595364,NaN
3,4933,1,Australian Terrier,1,110251,Australian Terrier,F,7,N,NaN,t,f,28001,Madrid,3,PET3,1250.0,1000.0,0.0,19.49,222.58,2026-04-11 09:04:10.074353,595366,NaN
4,4934,1,Australian Terrier,1,110251,Australian Terrier,M,7,S,NaN,t,f,28001,Madrid,3,PET3,1250.0,1000.0,0.0,18.86,215.43,2026-04-11 09:04:19.49232,595369,NaN

## 4.1 Dimensiones del dataset

### Objetivo

Verificar el número de registros y variables disponibles en el conjunto de datos para comprobar que coincide con la información obtenida durante el EDA.

### Implementación

In [5]:
print(f"Número de registros: {df.shape[0]}")
print(f"Número de variables: {df.shape[1]}")

Número de registros: 67500
Número de variables: 24

### Conclusiones

El dataset está compuesto por **67.500 registros** y **24 variables**, coincidiendo con la información obtenida durante el EDA.

### Decisión

No se identifican acciones de preprocesamiento derivadas de esta revisión.

## 4.2 Información general del dataset

### Objetivo

Revisar la estructura general del conjunto de datos, incluyendo los nombres de las variables, los tipos de datos y la cantidad de valores no nulos por columna.

### Implementación

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 67500 entries, 0 to 67499
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  67500 non-null  int64
 1   grupo_raza          67500 non-null  int64
 2   grupo_raza_nombre   67500 non-null  str
 3   pet_species         67500 non-null  int64
 4   pet_race_code       67500 non-null  int64
 5   pet_race_name       67500 non-null  str
 6   pet_gender          67500 non-null  str
 7   pet_age_nr          67500 non-null  int64
 8   pet_sterilized      67500 non-null  str
 9   sterilized_when     27000 non-null  str
 10  is_pure_breed       67500 non-null  str
 11  is_dangerous        67500 non-null  str
 12  owner_postal_code   67500 non-null  int64
 13  owner_municipality  67460 non-null  str
 14  plan_code           67500 non-null  int64
 15  plan_name           67500 non-null  str
 16  capital_vet_total   67500 non-null  float64
 17  capital_vet_plus    67500 non-null  float64
 18  capital_rc          67500 non-null  float64
 19  precio_mensual      67500 non-null  float64
 20  precio_anual        67500 non-null  float64
 21  fecha_cotizacion    67500 non-null  str
 22  multisimulation_id  67500 non-null  int64
 23  api_response        0 non-null      float64
dtypes: float64(6), int64(8), str(10)
memory usage: 12.4 MB

### Conclusiones

- El dataset fue cargado correctamente.
- Se identifican variables numéricas y categóricas que requerirán diferentes estrategias de transformación.
- Se detectan variables con valores faltantes que serán revisadas posteriormente.

### Decisión

Continuar con la revisión detallada de tipos de datos y valores nulos antes de definir las estrategias de limpieza.Ç

## 4.3 Distribución de tipos de datos

### Objetivo

Identificar cuántas variables numéricas y categóricas contiene el dataset, con el fin de anticipar las transformaciones que podrían ser necesarias durante el preprocesamiento.

### Implementación

In [7]:
tipos_datos = (
    df.dtypes
    .astype(str)
    .value_counts()
    .rename_axis("Tipo de dato")
    .reset_index(name="Cantidad de variables")
)

tipos_datos

  Tipo de dato  Cantidad de variables
0          str                     10
1        int64                      8
2      float64                      6

### Conclusiones

- El dataset contiene variables numéricas enteras, numéricas continuas y categóricas.
- Será necesario aplicar diferentes técnicas de transformación según el tipo de dato de cada variable.

### Decisión

La estrategia de codificación y transformación se definirá posteriormente durante el preprocesamiento, clasificando las variables según su naturaleza.

## 4.4 Revisión de valores nulos

### Objetivo

Identificar las variables que contienen valores faltantes y cuantificar su proporción dentro del dataset, teniendo en cuenta que algunos nulos pueden formar parte de la lógica natural del negocio.

### Implementación

In [8]:
resumen_nulos = (
    pd.DataFrame({
        "valores nulos": df.isna().sum(),
        "porcentaje nulos": (df.isna().mean() * 100).round(2)
    })
    .query("`valores nulos` > 0")
    .sort_values("porcentaje nulos", ascending=False)
)

resumen_nulos

                    valores nulos  porcentaje nulos
api_response                67500            100.00
sterilized_when             40500             60.00
owner_municipality             40              0.06

### Conclusiones

Se identificaron tres variables con valores faltantes:

- **api_response** presenta un 100 % de valores nulos.
- **sterilized_when** presenta un 60 % de valores nulos, aunque parte de estos valores responden a la lógica del negocio.
- **owner_municipality** presenta únicamente un 0,06 % de valores nulos.

### Decisión

- Evaluar la eliminación de **api_response** por no contener información útil.
- Analizar el significado de los valores faltantes de **sterilized_when** antes de aplicar cualquier tratamiento.
- Revisar posteriormente la estrategia más adecuada para tratar los pocos valores faltantes de **owner_municipality**.

## 4.5 Revisión de registros duplicados

### Objetivo

Comprobar si existen filas completamente duplicadas que puedan alterar el análisis o generar sesgos durante el entrenamiento del modelo.

### Implementación

In [9]:
duplicados = pd.DataFrame({
    "Métrica": ["Registros duplicados"],
    "Valor": [df.duplicated().sum()]
})

duplicados

                Métrica  Valor
0  Registros duplicados      0

### Conclusiones

No se identificaron registros completamente duplicados en el conjunto de datos.

### Decisión

No será necesario aplicar procesos de eliminación de registros duplicados durante el preprocesamiento.

# 5. Revisión de variables candidatas para el modelo

## Objetivo

Analizar las variables del conjunto de datos para identificar aquellas que aportarán valor al modelo de Machine Learning y detectar posibles variables técnicas, redundantes o con riesgo de generar Data Leakage.

Las decisiones tomadas en esta etapa servirán como base para el proceso de limpieza y selección de variables que se realizará durante el preprocesamiento.

## 5.1 Variables técnicas e identificadores

### Objetivo

Revisar las variables utilizadas como identificadores o con fines exclusivamente técnicos para determinar si aportan información útil al modelo o si deben excluirse del proceso de entrenamiento.

### Implementación

In [11]:
variables_tecnicas = [
    "id",
    "multisimulation_id",
    "api_response"
]

resumen_tecnicas = pd.DataFrame({
    "Variable": variables_tecnicas,
    "Valores únicos": [df[col].nunique(dropna=False) for col in variables_tecnicas],
    "Valores nulos": [df[col].isna().sum() for col in variables_tecnicas]
})

resumen_tecnicas

             Variable  Valores únicos  Valores nulos
0                  id           67500              0
1  multisimulation_id           67500              0
2        api_response               1          67500

### Conclusiones

Tras revisar las variables técnicas e identificadores se obtuvieron las siguientes observaciones:

- **id** presenta un valor único para cada registro, por lo que actúa únicamente como identificador y no aporta información predictiva para el modelo.
- **multisimulation_id** también corresponde a un identificador técnico con un valor único por registro, por lo que tampoco aporta capacidad predictiva.
- **api_response** presenta un **100 % de valores nulos**, por lo que no contiene información útil para el proceso de entrenamiento.

### Decisión

Se eliminarán las variables **id**, **multisimulation_id** y **api_response**, ya que corresponden a identificadores técnicos o no contienen información útil para el entrenamiento del modelo.

## 5.2 Variables redundantes

### Objetivo

Comprobar si existen variables que representan la misma información mediante diferentes formatos (códigos y nombres), con el fin de evitar redundancias durante el entrenamiento del modelo.

In [12]:
(
    df.groupby("grupo_raza")["grupo_raza_nombre"]
      .nunique()
      .value_counts()
)

grupo_raza_nombre
1    25
Name: count, dtype: int64

In [13]:
(
    df.groupby("pet_race_code")["pet_race_name"]
      .nunique()
      .value_counts()
)

pet_race_name
1    25
Name: count, dtype: int64

In [14]:
(
    df.groupby("plan_code")["plan_name"]
      .nunique()
      .value_counts()
)

plan_name
1    2
Name: count, dtype: int64

### Conclusiones

El análisis muestra que las siguientes parejas de variables mantienen una correspondencia uno a uno:

- **grupo_raza** ↔ **grupo_raza_nombre**
- **pet_race_code** ↔ **pet_race_name**
- **plan_code** ↔ **plan_name**

Esto indica que ambas variables de cada pareja representan la misma información utilizando dos formatos distintos: un código numérico y un nombre descriptivo.

### Decisión

Para evitar redundancias durante el entrenamiento del modelo, se conservará únicamente una variable de cada pareja.

La selección definitiva se realizará durante el preprocesamiento, priorizando aquellas variables que faciliten la interpretación de los resultados y la implementación del pipeline de Machine Learning.

## 5.3 Variable objetivo y riesgo de Data Leakage

### Objetivo

Verificar la relación existente entre la variable objetivo (`precio_mensual`) y la variable `precio_anual`, con el fin de identificar posibles riesgos de **Data Leakage** antes del entrenamiento del modelo.

### Implementación

In [16]:
comparacion_precios = pd.DataFrame({
    "precio_mensual": df["precio_mensual"],
    "precio_mensual_x12": (df["precio_mensual"] * 12).round(2),
    "precio_anual": df["precio_anual"]
})

comparacion_precios.head(10)

   precio_mensual  precio_mensual_x12  precio_anual
0           19.30              231.60        220.40
1           18.53              222.36        211.62
2           19.08              228.96        217.94
3           19.49              233.88        222.58
4           18.86              226.32        215.43
5           19.30              231.60        220.40
6           18.53              222.36        211.62
7           19.08              228.96        217.94
8           19.49              233.88        222.58
9           18.86              226.32        215.43

In [17]:
coinciden = (
    (df["precio_mensual"] * 12)
    .round(2)
    .equals(df["precio_anual"].round(2))
)

resultado_leakage = pd.DataFrame({
    "Comprobación": ["¿precio_anual = precio_mensual × 12?"],
    "Resultado": [coinciden]
})

resultado_leakage

                           Comprobación  Resultado
0  ¿precio_anual = precio_mensual × 12?      False

### Análisis complementario

La comprobación inicial mostró que **precio_anual** no corresponde exactamente al valor de **precio_mensual × 12**.

Por este motivo, se realiza un análisis adicional para comprender la relación existente entre ambas variables y determinar si **precio_anual** sigue representando una transformación derivada de la variable objetivo.

In [18]:
comparacion_precios["descuento"] = (
    comparacion_precios["precio_mensual_x12"]
    - comparacion_precios["precio_anual"]
).round(2)

comparacion_precios["descuento"].describe()

count    67500.000000
mean        18.859041
std          6.119087
min          7.710000
25%         14.230000
50%         17.720000
75%         22.370000
max         53.000000
Name: descuento, dtype: float64

In [19]:
relacion = (
    df["precio_anual"] / df["precio_mensual"]
).round(4)

relacion.describe()

count    67500.000000
mean        11.419787
std          0.002455
min         11.408100
25%         11.418300
50%         11.419800
75%         11.421300
max         11.432900
dtype: float64

### Conclusiones

La comprobación realizada muestra que **precio_anual** no corresponde exactamente al valor de **precio_mensual × 12**.

Sin embargo, el análisis evidencia que ambas variables mantienen una relación prácticamente constante, con un factor medio cercano a **11,42**, lo que indica que **precio_anual** se obtiene mediante una transformación comercial derivada directamente del **precio_mensual**.

La reducida variabilidad observada en dicha relación sugiere la existencia de una regla de negocio estable, posiblemente asociada a descuentos o condiciones comerciales aplicadas a las cotizaciones anuales.

### Decisión

La variable **precio_anual** será eliminada del conjunto de variables predictoras.

Aunque no representa exactamente el valor de **precio_mensual × 12**, continúa siendo una variable derivada directamente de la variable objetivo y su utilización durante el entrenamiento introduciría **Data Leakage**, proporcionando al modelo información que no estaría disponible en una nueva cotización.

>*Hallazgo*
>
> El análisis permitió identificar que **precio_anual** no es simplemente el resultado de multiplicar el precio mensual x 12, sino que incorpora una transformación comercial consistente. Aun así, mantiene una dependencia directa con la variable objetivo, por lo que no debe utilizarse como variable predictora.

In [20]:
factor_plan = (
    df.assign(
        factor_anual=df["precio_anual"] / df["precio_mensual"]
    )
    .groupby("plan_name")["factor_anual"]
    .agg(["mean", "std", "min", "max"])
    .round(4)
)

factor_plan

              mean     std      min      max
plan_name
PET VITAL  11.4198  0.0018  11.4132  11.4265
PET3       11.4198  0.0027  11.4081  11.4329

### Conclusiones

La comprobación realizada muestra que **precio_anual** no corresponde exactamente al valor de **precio_mensual × 12**.

No obstante, el análisis evidencia que ambas variables mantienen una relación prácticamente constante, con un factor medio cercano a **11,42**.

Adicionalmente, al analizar dicha relación por tipo de plan, se observa que el factor permanece prácticamente invariable entre los distintos planes comerciales disponibles.

Estos resultados indican que **precio_anual** se obtiene mediante una transformación comercial derivada directamente del **precio_mensual**, aplicada de forma consistente en todo el conjunto de datos.

### Decisión

La variable **precio_anual** será eliminada del conjunto de variables predictoras.

Aunque no representa exactamente el valor de **precio_mensual × 12**, continúa siendo una variable derivada directamente de la variable objetivo y su utilización durante el entrenamiento introduciría **Data Leakage**, proporcionando al modelo información que no estaría disponible en una nueva cotización.

> **Hallazgo validado con el experto de negocio**
>
> El análisis permitió identificar que `precio_anual` no corresponde simplemente a doce mensualidades, sino que incorpora una transformación comercial prácticamente constante respecto a `precio_mensual`.
>
> Tras validar este comportamiento con el experto de negocio, se confirmó que las cotizaciones con modalidad de pago anual incluyen un descuento aproximado del 5 %. Esta regla explica que el factor observado entre ambas variables sea cercano a 11,42 en lugar de 12.
>
> Las pequeñas variaciones detectadas pueden estar relacionadas con los procesos de cálculo y redondeo aplicados por el sistema de cotización.

## 5.4 Variables geográficas

### Objetivo

Analizar las variables geográficas del conjunto de datos para comprender su estructura, detectar posibles inconsistencias y evaluar su utilidad dentro del modelo de Machine Learning.

### Implementación

In [21]:
resumen_geo = pd.DataFrame({
    "Variable": ["owner_postal_code", "owner_municipality"],
    "Valores únicos": [
        df["owner_postal_code"].nunique(),
        df["owner_municipality"].nunique()
    ]
})

resumen_geo

             Variable  Valores únicos
0   owner_postal_code               5
1  owner_municipality               5

In [22]:
municipios_por_cp = (
    df.groupby("owner_postal_code")["owner_municipality"]
      .nunique(dropna=True)
      .reset_index(name="Municipios por código postal")
)

municipios_por_cp

   owner_postal_code  Municipios por código postal
0               2124                             2
1               2210                             1
2              28001                             1
3              28220                             1
4              50001                             1

In [23]:
cp_por_municipio = (
    df.groupby("owner_municipality")["owner_postal_code"]
      .nunique()
      .reset_index(name="Códigos postales por municipio")
)

cp_por_municipio

  owner_municipality  Códigos postales por municipio
0           Albacete                               1
1   Alcalá del Júcar                               1
2             Madrid                               1
3        Majadahonda                               1
4           Zaragoza                               2

In [26]:
combinaciones_geograficas = (
    df[["owner_postal_code", "owner_municipality"]]
    .drop_duplicates()
    .sort_values(["owner_postal_code", "owner_municipality"])
)

combinaciones_geograficas

       owner_postal_code owner_municipality
32448               2124           Albacete
18947               2124           Zaragoza
49819               2210   Alcalá del Júcar
0                  28001             Madrid
67461              28001                NaN
38146              28220        Majadahonda
8137               50001           Zaragoza
67460              50001                NaN

### Conclusiones

El análisis confirma que el dataset contiene **cinco códigos postales** y **cinco municipios**, lo que resulta coherente con la estructura simplificada del conjunto de datos.

Tras validar este comportamiento con el experto de negocio, se confirmó que el sistema de cotización organiza el territorio en **cinco zonas tarifarias**. Cada zona agrupa diferentes códigos postales y aplica una misma tarifa geográfica, siendo la zona 5 la de mayor coste.

También se identificaron algunas combinaciones en las que un mismo código postal aparece asociado a más de un municipio y un municipio aparece vinculado con más de un código postal.

Debido a la naturaleza parcialmente simulada del dataset, estas combinaciones no se modificarán sin contar con evidencia suficiente de que correspondan a errores de calidad.

### Decisión

- Se conservarán inicialmente `owner_postal_code` y `owner_municipality` como variables candidatas para el modelo.
- `owner_postal_code` será tratado como una variable categórica y no como una cantidad numérica.
- Durante el preprocesamiento se convertirá a texto y se completarán los ceros iniciales para mantener el formato estándar de cinco dígitos.
- No se modificarán manualmente las asociaciones entre códigos postales y municipios.
- La utilidad y posible redundancia de ambas variables se evaluará posteriormente mediante el rendimiento y la interpretación de los modelos.


> **Hallazgo validado con el experto de negocio**
>
> Las variables geográficas representan una simplificación del sistema de tarificación de la aseguradora, basado en cinco zonas geográficas con tarifas diferenciadas. Esto explica el reducido número de códigos postales y municipios presentes en el dataset.

# 6. Revisión detallada de variables

## Objetivo

Analizar individualmente las variables que formarán parte del modelo con el fin de comprender su comportamiento, validar su consistencia y definir la estrategia de preprocesamiento más adecuada para cada una de ellas.

En esta fase no se realizarán transformaciones sobre el dataset original. El objetivo es documentar las decisiones que posteriormente serán implementadas durante el preprocesamiento.

In [57]:
variables_categoricas = [
    "grupo_raza_nombre",
    "pet_race_name",
    "plan_name",
    "owner_municipality"
]

variables_binarias = [
    "pet_gender",
    "pet_sterilized",
    "is_pure_breed",
    "is_dangerous"
]

variables_ordinales = [
    "sterilized_when"
]

variables_numericas = [
    "pet_age_nr",
    "capital_vet_total",
    "capital_vet_plus",
    "capital_rc",
    "precio_mensual",
    "precio_anual"
]

## 6.1 Variables categóricas nominales

### Objetivo

Revisar las variables categóricas nominales para identificar el número de categorías existentes, detectar posibles inconsistencias y definir la estrategia de codificación que se aplicará posteriormente durante el preprocesamiento.

### Implementación

### Función: `revisar_variable_categorica()`

Con el fin de evitar la repetición de código durante el análisis de las variables categóricas, se define una función reutilizable que resume automáticamente la información más relevante de cada variable.

La función muestra:

- El nombre de la variable.
- El número de valores únicos.
- El número de valores nulos.
- La frecuencia absoluta de cada categoría.
- El porcentaje que representa cada categoría respecto al total de registros.
Esta función será utilizada durante la revisión de todas las variables categóricas del proyecto.

In [35]:
def revisar_variable_categorica(df, columna):
    """
    Analiza una variable categórica mostrando un resumen estadístico
    y la distribución de sus categorías.

    Esta función se utiliza durante la fase de revisión del dataset
    para apoyar la toma de decisiones del preprocesamiento.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene la información.

    columna : str
        Nombre de la variable categórica que se desea analizar.

    Salida
    -------
    Muestra dos tablas:

    1. Resumen general
        - Nombre de la variable.
        - Número de valores únicos.
        - Número de valores nulos.

    2. Distribución de categorías
        - Frecuencia absoluta.
        - Porcentaje respecto al total de registros.
    """

    # ==========================================================
    # Resumen general de la variable
    # ==========================================================
    resumen = pd.DataFrame({
        "Variable": [columna],
        "Valores únicos": [df[columna].nunique(dropna=False)],
        "Valores nulos": [df[columna].isna().sum()]
    })

    display(resumen)

    # ==========================================================
    # Distribución de frecuencias y porcentaje
    # ==========================================================
    frecuencias = (
        df[columna]
        .value_counts(dropna=False)
        .rename("Frecuencia")
        .to_frame()
    )

    frecuencias["Porcentaje (%)"] = (
        frecuencias["Frecuencia"] / len(df) * 100
    ).round(2)

    display(frecuencias)

### Utilidad de la función

La función `revisar_variable_categorica()` permite automatizar el análisis de las variables categóricas del conjunto de datos, facilitando la identificación de:

- categorías poco frecuentes;
- valores nulos;
- distribuciones desequilibradas;
- posibles situaciones que puedan requerir tratamiento durante el preprocesamiento.

El uso de una función reutilizable garantiza un análisis homogéneo para todas las variables y mejora la legibilidad, mantenibilidad y escalabilidad del notebook.

In [58]:
for variable in variables_categoricas:
    revisar_variable_categorica(df, variable)

            Variable  Valores únicos  Valores nulos
0  grupo_raza_nombre              25              0

                                                    Frecuencia  Porcentaje (%)
grupo_raza_nombre
Mestizo Gigante (Más de 45 Kg)                            4500            6.67
Mestizo Mediano (Entre 11 y 20 Kg)                        4500            6.67
Mestizo Grande (Entre 21 y 45 Kg)                         4500            6.67
Mestizo Pequeño (Entre 5 y 10 Kg)                         4500            6.67
Mestizo Miniatura (Menos de 5 Kg)                         4500            6.67
Australian Terrier                                        2250            3.33
Biewer Terrier                                            2250            3.33
Anglo-Francais De Petite Venerie                          2250            3.33
Bull Terrier                                              2250            3.33
Caniche Enano (Poodle Mini)                               2250            3.33
Caniche Miniatura (Poodle Toy)                            2250            3.33
Airedale Terrier                                          2250            3.33
Beagle                                                    2250            3.33
American Staffordshire Terrier                            2250            3.33
Affenpinscher                                             2250            3.33
Spaniel Continental Enano De Compañía (Papillon...        2250            3.33
Balinés                                                   2250            3.33
Akita Inu                                                 2250            3.33
Akita Americano (G Perro Japones)                         2250            3.33
Gato Común/European Shorthair Cat                         2250            3.33
Abisinio                                                  2250            3.33
Exotic                                                    2250            3.33
Shar Pei                                                  2250            3.33
Boxer                                                     2250            3.33
Bullmastiff                                               2250            3.33

        Variable  Valores únicos  Valores nulos
0  pet_race_name              25              0

                                                    Frecuencia  Porcentaje (%)
pet_race_name
Mestizo Gigante (Más de 45 Kg)                            4500            6.67
Mestizo Mediano (Entre 11 y 20 Kg)                        4500            6.67
Mestizo Grande (Entre 21 y 45 Kg)                         4500            6.67
Mestizo Pequeño (Entre 5 y 10 Kg)                         4500            6.67
Mestizo Miniatura (Menos de 5 Kg)                         4500            6.67
Australian Terrier                                        2250            3.33
Biewer Terrier                                            2250            3.33
Anglo-Francais De Petite Venerie                          2250            3.33
Bull Terrier                                              2250            3.33
Caniche Enano (Poodle Mini)                               2250            3.33
Caniche Miniatura (Poodle Toy)                            2250            3.33
Airedale Terrier                                          2250            3.33
Beagle                                                    2250            3.33
American Staffordshire Terrier                            2250            3.33
Affenpinscher                                             2250            3.33
Spaniel Continental Enano De Compañía (Papillon...        2250            3.33
Balinés                                                   2250            3.33
Akita Inu                                                 2250            3.33
Akita Americano (G Perro Japones)                         2250            3.33
Gato Común/European Shorthair Cat                         2250            3.33
Abisinio                                                  2250            3.33
Exotic                                                    2250            3.33
Shar Pei                                                  2250            3.33
Boxer                                                     2250            3.33
Bullmastiff                                               2250            3.33

    Variable  Valores únicos  Valores nulos
0  plan_name               2              0

           Frecuencia  Porcentaje (%)
plan_name
PET3            45000           66.67
PET VITAL       22500           33.33

             Variable  Valores únicos  Valores nulos
0  owner_municipality               6             40

                    Frecuencia  Porcentaje (%)
owner_municipality
Zaragoza                 26977           39.97
Majadahonda              13500           20.00
Alcalá del Júcar         13500           20.00
Madrid                   13480           19.97
NaN                         40            0.06
Albacete                     3            0.00

### Conclusiones

Las variables categóricas nominales presentan una estructura consistente y un número reducido de categorías, lo que facilita su utilización en el proceso de modelado.

Las variables `grupo_raza_nombre` y `pet_race_name` no presentan valores nulos y muestran una distribución controlada, coherente con la naturaleza parcialmente simulada del conjunto de datos.

La variable `plan_name` contiene únicamente dos categorías, correspondientes a los planes comerciales disponibles.

En `owner_municipality` únicamente se identifican 40 valores nulos y tres registros asociados a la categoría **Albacete**, cuya frecuencia resulta significativamente inferior al resto de municipios. Dado el carácter parcialmente simulado del dataset, estos registros se conservarán sin modificaciones hasta completar el preprocesamiento.

### Decisión

Las variables categóricas nominales se conservarán para el entrenamiento del modelo.

Durante el preprocesamiento se aplicará la estrategia de codificación correspondiente a cada algoritmo, manteniendo inicialmente todas las categorías observadas.

No se realizarán agrupaciones ni eliminaciones de categorías en esta fase del análisis.

### Función auxiliar: `revisar_variable_binaria()`

Con el objetivo de estandarizar el análisis de las variables binarias, se define una función reutilizable que resume sus principales características y facilita la revisión del dataset durante la fase de preprocesamiento.

La función muestra:

- Información general de la variable.
- Número de categorías.
- Valores nulos.
- Distribución de frecuencias.
- Porcentaje de cada categoría.
- Validación de que la variable contiene únicamente dos categorías no nulas.

In [36]:
def revisar_variable_binaria(df, columna):
    """
    Analiza una variable binaria mostrando un resumen de sus categorías,
    valores nulos y distribución.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene la información.

    columna : str
        Nombre de la variable binaria que se desea analizar.

    Salida
    -------
    Muestra dos tablas:

    1. Resumen general
        - Nombre de la variable.
        - Número de valores únicos no nulos.
        - Número de valores nulos.
        - Validación de estructura binaria.

    2. Distribución de categorías
        - Frecuencia absoluta.
        - Porcentaje respecto al total de registros.
    """

    # Resumen general de la variable
    valores_unicos = df[columna].dropna().nunique()

    resumen = pd.DataFrame({
        "Variable": [columna],
        "Valores únicos no nulos": [valores_unicos],
        "Valores nulos": [df[columna].isna().sum()],
        "¿Es binaria?": [valores_unicos == 2]
    })

    display(resumen)

    # Distribución de frecuencias y porcentaje
    frecuencias = (
        df[columna]
        .value_counts(dropna=False)
        .rename("Frecuencia")
        .to_frame()
    )

    frecuencias["Porcentaje (%)"] = (
        frecuencias["Frecuencia"] / len(df) * 100
    ).round(2)

    display(frecuencias)

In [59]:
for variable in variables_binarias:
    revisar_variable_binaria(df, variable)

     Variable  Valores únicos no nulos  Valores nulos  ¿Es binaria?
0  pet_gender                        2              0          True

            Frecuencia  Porcentaje (%)
pet_gender
F                40500            60.0
M                27000            40.0

         Variable  Valores únicos no nulos  Valores nulos  ¿Es binaria?
0  pet_sterilized                        2              0          True

                Frecuencia  Porcentaje (%)
pet_sterilized
S                    40500            60.0
N                    27000            40.0

        Variable  Valores únicos no nulos  Valores nulos  ¿Es binaria?
0  is_pure_breed                        2              0          True

               Frecuencia  Porcentaje (%)
is_pure_breed
t                   45000           66.67
f                   22500           33.33

       Variable  Valores únicos no nulos  Valores nulos  ¿Es binaria?
0  is_dangerous                        2              0          True

              Frecuencia  Porcentaje (%)
is_dangerous
f                  56250           83.33
t                  11250           16.67

### Conclusiones

Las cuatro variables binarias presentan una estructura consistente, sin valores nulos y con únicamente dos categorías válidas, por lo que son adecuadas para ser utilizadas en el proceso de modelado.

Se observa que:

- `pet_gender` presenta una distribución del 60 % de hembras y 40 % de machos.
- `pet_sterilized` mantiene la misma distribución, con un 60 % de mascotas esterilizadas y un 40 % no esterilizadas.
- `is_pure_breed` indica que aproximadamente dos terceras partes de las mascotas corresponden a razas puras.
- `is_dangerous` muestra que únicamente el 16,67 % de los registros pertenecen a razas catalogadas como potencialmente peligrosas.

No se detectan inconsistencias ni categorías inesperadas en ninguna de las variables analizadas.

### Decisión

Las variables binarias se conservarán para el entrenamiento del modelo.

Durante el preprocesamiento:

- Las variables booleanas (`is_pure_breed` e `is_dangerous`) se transformarán a una representación binaria (`0` y `1`).
- Las variables categóricas binarias (`pet_gender` y `pet_sterilized`) también serán codificadas en formato binario para facilitar su utilización por los algoritmos de Machine Learning.

Esta transformación se realizará durante la implementación del pipeline de preprocesamiento, manteniendo intacto el dataset original durante la fase de análisis.

> **Hallazgo**
>
>Todas las variables binarias presentan una estructura completamente consistente, sin valores nulos y con únicamente dos categorías válidas.
>
>Esta característica simplificará el proceso de preprocesamiento, ya que permitirá aplicar una codificación binaria directa sin necesidad de realizar tratamientos adicionales de limpieza.

## 6.3 Variables ordinales

### Objetivo

Analizar las variables ordinales del conjunto de datos para validar sus categorías, identificar posibles valores nulos y determinar la estrategia de codificación más adecuada durante el preprocesamiento.

En esta fase se revisará la variable `sterilized_when`, ya que sus categorías representan un orden natural relacionado con el momento en que la mascota fue esterilizada.

### Función auxiliar: `revisar_variable_ordinal()`

Con el fin de mantener un criterio homogéneo durante el análisis, se define una función reutilizable para revisar variables ordinales.

La función muestra:

- Nombre de la variable.
- Número de categorías.
- Valores nulos.
- Distribución de frecuencias.
- Porcentaje de cada categoría.

In [38]:
def revisar_variable_ordinal(df, columna):
    """
    Analiza una variable ordinal mostrando un resumen estadístico
    y la distribución de sus categorías.

    Esta función se utiliza durante la fase de revisión del dataset
    para apoyar la toma de decisiones del preprocesamiento.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene la información.

    columna : str
        Nombre de la variable ordinal.

    Salida
    -------
    Muestra dos tablas:

    1. Resumen general.
    2. Distribución de categorías con frecuencia y porcentaje.
    """

    # ==========================================================
    # Resumen general
    # ==========================================================

    resumen = pd.DataFrame({
        "Variable": [columna],
        "Valores únicos": [df[columna].nunique(dropna=False)],
        "Valores nulos": [df[columna].isna().sum()]
    })

    display(resumen)

    # ==========================================================
    # Distribución
    # ==========================================================

    frecuencias = (
        df[columna]
        .value_counts(dropna=False)
        .rename("Frecuencia")
        .to_frame()
    )

    frecuencias["Porcentaje (%)"] = (
        frecuencias["Frecuencia"] / len(df) * 100
    ).round(2)

    display(frecuencias)

In [39]:
revisar_variable_ordinal(df, "sterilized_when")

          Variable  Valores únicos  Valores nulos
0  sterilized_when               3          40500

                 Frecuencia  Porcentaje (%)
sterilized_when
NaN                   40500            60.0
S2                    13500            20.0
S3                    13500            20.0

In [40]:
pd.crosstab(
    df["pet_sterilized"],
    df["sterilized_when"].fillna("No aplica"),
    margins=True
)

sterilized_when  No aplica     S2     S3    All
pet_sterilized
N                    27000      0      0  27000
S                    13500  13500  13500  40500
All                  40500  13500  13500  67500

In [42]:
pd.crosstab(
    [df["pet_gender"], df["pet_sterilized"]],
    df["sterilized_when"].fillna("No aplica"),
    margins=True
)

sterilized_when            No aplica     S2     S3    All
pet_gender pet_sterilized
F          N                   13500      0      0  13500
           S                       0  13500  13500  27000
M          N                   13500      0      0  13500
           S                   13500      0      0  13500
All                            40500  13500  13500  67500

### Conclusiones

La variable `sterilized_when` presenta tres estados observados:

- S2
- S3
- Valores nulos

El análisis conjunto con `pet_gender` y `pet_sterilized` demuestra que los valores nulos no representan datos faltantes, sino situaciones en las que el momento de la esterilización no aplica.

En concreto:

- Las hembras esterilizadas se clasifican entre `S2` y `S3`.
- Las hembras no esterilizadas presentan un valor nulo.
- Todos los machos presentan un valor nulo, independientemente de si están esterilizados o no, ya que el concepto de esterilización antes o después del celo únicamente aplica a las hembras.

Por tanto, los valores nulos poseen un significado funcional dentro del negocio y no deben interpretarse como un problema de calidad del dataset.

### Decisión

La variable `sterilized_when` se conservará para el entrenamiento del modelo.

Durante el preprocesamiento no se imputarán sus valores nulos mediante técnicas estadísticas, ya que representan una condición válida del negocio.

Si el algoritmo utilizado requiere variables sin valores nulos, estos registros podrán transformarse explícitamente en la categoría **"No aplica"**, preservando su significado original.

>### Hallazgo
>
>El análisis permitió comprobar que `sterilized_when` únicamente aporta información para las mascotas hembra esterilizadas.
>
>Los valores nulos no representan pérdida de información, sino una condición inherente al negocio, ya que el momento de la esterilización solo resulta aplicable cuando la mascota es una hembra esterilizada.
>
>Este comportamiento permitirá definir una estrategia de preprocesamiento basada en el significado de la variable y no únicamente en la presencia de valores nulos.

> ** Nota técnica para el equipo**
>
> La variable `sterilized_when` **no debe tratarse como una variable independiente**, ya que su interpretación depende directamente de dos variables:
>
> - `pet_gender`
> - `pet_sterilized`
>
> El análisis realizado demuestra que:
>
> - Solo las **hembras esterilizadas** presentan valores `S2` o `S3`.
> - Las **hembras no esterilizadas** presentan un valor nulo.
> - Todos los **machos** presentan un valor nulo, independientemente de si están esterilizados o no, ya que el concepto de esterilización antes o después del celo únicamente aplica a las hembras.
>
> En consecuencia:
>
> - Los valores nulos **no representan datos faltantes**.
> - No deben imputarse mediante técnicas estadísticas.
> - Cualquier transformación deberá preservar la lógica de negocio observada en el dataset.

## 6.4 Variable temporal

### Objetivo

Analizar la variable temporal `fecha_cotizacion` para conocer su estructura, el período temporal representado en el dataset y determinar si aporta información relevante para el modelo de Machine Learning.

En esta fase únicamente se realizará el análisis de la variable. Cualquier transformación será implementada posteriormente durante el preprocesamiento.

### Función auxiliar: `revisar_variable_temporal()`

Se define una función reutilizable para analizar variables temporales.

La función resume:

- Tipo de dato.
- Número de fechas distintas.
- Fecha mínima.
- Fecha máxima.
- Valores nulos.

In [46]:
def revisar_variable_temporal(df, columna):
    """
    Analiza una variable temporal mostrando un resumen de su estructura.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene la información.

    columna : str
        Nombre de la variable temporal.

    Salida
    -------
    Muestra un resumen con:

    - Tipo de dato.
    - Número de fechas distintas.
    - Fecha mínima.
    - Fecha máxima.
    - Valores nulos.
    """

    fechas = pd.to_datetime(df[columna])

    resumen = pd.DataFrame({
        "Variable": [columna],
        "Tipo de dato": [fechas.dtype],
        "Fechas distintas": [fechas.dt.date.nunique()],
        "Fecha mínima": [fechas.min()],
        "Fecha máxima": [fechas.max()],
        "Valores nulos": [fechas.isna().sum()]
    })

    display(resumen)

In [47]:
revisar_variable_temporal(df, "fecha_cotizacion")

,Variable,Tipo de dato,Fechas distintas,Fecha mínima,Fecha máxima,Valores nulos
0,fecha_cotizacion,datetime64[us],11,2026-04-11 09:03:45.882914,2026-04-21 14:39:13.907064,0

In [48]:
(
    pd.to_datetime(df["fecha_cotizacion"])
      .dt.date
      .value_counts()
      .sort_index()
)

fecha_cotizacion
2026-04-11    5684
2026-04-12    4999
2026-04-13    6275
2026-04-14    8546
2026-04-15    5015
2026-04-16    5305
2026-04-17    6016
2026-04-18    9322
2026-04-19    8743
2026-04-20    5883
2026-04-21    1712
Name: count, dtype: int64

In [49]:
precio_por_dia = (
    df.groupby(pd.to_datetime(df["fecha_cotizacion"]).dt.date)
      .agg(
          Cotizaciones=("precio_mensual", "count"),
          Precio_medio=("precio_mensual", "mean"),
          Precio_min=("precio_mensual", "min"),
          Precio_max=("precio_mensual", "max")
      )
      .round(2)
)

display(precio_por_dia)

                  Cotizaciones  Precio_medio  Precio_min  Precio_max
fecha_cotizacion
2026-04-11                5684         34.24       18.53       65.12
2026-04-12                4999         31.06       15.61       63.18
2026-04-13                6275         35.17       16.35       82.06
2026-04-14                8546         30.87       14.60       61.80
2026-04-15                5015         28.67       13.94       56.63
2026-04-16                5305         36.04       15.61       87.70
2026-04-17                6016         30.93       16.06       72.63
2026-04-18                9322         36.89       16.26       91.45
2026-04-19                8743         31.10       15.47       70.68
2026-04-20                5883         30.04       13.27       73.97
2026-04-21                1712         26.94       14.84       74.53

### Conclusiones

La variable `fecha_cotizacion` recoge cotizaciones realizadas entre el 11 y el 21 de abril de 2026, abarcando un período de once días consecutivos.

Aunque se observan diferencias en el precio medio diario, el horizonte temporal analizado es demasiado reducido para identificar tendencias, estacionalidad o patrones temporales que puedan considerarse representativos del negocio.

Por tanto, las variaciones observadas entre días no permiten atribuir un efecto explicativo a la fecha de cotización.

### Decisión

La variable `fecha_cotizacion` no se incorporará inicialmente como variable predictora del modelo.

No obstante, se conservará en el dataset durante la fase de análisis para facilitar posibles comprobaciones o validaciones adicionales.

En caso de disponer en el futuro de un histórico temporal más amplio, esta variable podrá reevaluarse para analizar posibles efectos estacionales o tendencias del mercado.

>### Hallazgo
>
>El conjunto de datos corresponde a un intervalo temporal reducido de once días consecutivos.
>
>Aunque existen diferencias entre los precios medios diarios, la duración del período analizado no permite concluir que la fecha de cotización constituya un factor explicativo del precio del seguro.
>
>**Nota metodológica**
>
>La decisión de no utilizar `fecha_cotizacion` como variable predictora se basa en el alcance temporal del dataset disponible y no implica que las variables temporales carezcan de utilidad en otros escenarios. Con un histórico >más amplio podrían derivarse nuevas características temporales (mes, estación, festivos, tendencias, etc.) potencialmente relevantes para el modelo.

## 6.5 Variables numéricas

### Objetivo

Analizar las variables numéricas continuas del conjunto de datos para identificar posibles anomalías, comprobar sus rangos de valores y documentar las transformaciones que podrían ser necesarias durante el preprocesamiento.

En esta fase únicamente se realizará una revisión descriptiva de las variables numéricas, dejando las transformaciones para el pipeline de Machine Learning.

### Función auxiliar: `revisar_variable_numerica()`

Con el fin de mantener un criterio homogéneo durante el análisis, se define una función reutilizable para revisar variables numéricas.

La función resume:

- Tipo de dato.
- Valores nulos.
- Estadísticos descriptivos.
- Número de valores únicos.

In [53]:
def revisar_variable_numerica(df, columna):
    """
    Analiza una variable numérica mostrando un resumen descriptivo.

    Parámetros
    ----------
    df : pandas.DataFrame
        DataFrame que contiene la información.

    columna : str
        Nombre de la variable numérica.

    Salida
    -------
    Muestra:

    1. Resumen general.
    2. Estadísticos descriptivos.
    """

    resumen = pd.DataFrame({
        "Variable": [columna],
        "Tipo de dato": [df[columna].dtype],
        "Valores únicos": [df[columna].nunique()],
        "Valores nulos": [df[columna].isna().sum()]
    })

    display(resumen)

    display(
        df[[columna]]
        .describe()
        .round(2)
    )

In [60]:
for variable in variables_numericas:
    revisar_variable_numerica(df, variable)

     Variable Tipo de dato  Valores únicos  Valores nulos
0  pet_age_nr        int64              10              0

       pet_age_nr
count    67500.00
mean         4.50
std          2.87
min          0.00
25%          2.00
50%          4.50
75%          7.00
max          9.00

            Variable Tipo de dato  Valores únicos  Valores nulos
0  capital_vet_total      float64               3              0

       capital_vet_total
count           67500.00
mean             2000.00
std               735.99
min              1250.00
25%              1250.00
50%              1750.00
75%              3000.00
max              3000.00

           Variable Tipo de dato  Valores únicos  Valores nulos
0  capital_vet_plus      float64               3              0

       capital_vet_plus
count          67500.00
mean            1583.33
std              513.70
min             1000.00
25%             1000.00
50%             1500.00
75%             2250.00
max             2250.00

     Variable Tipo de dato  Valores únicos  Valores nulos
0  capital_rc      float64               3              0

       capital_rc
count    67500.00
mean    150000.00
std     122475.39
min          0.00
25%          0.00
50%     150000.00
75%     300000.00
max     300000.00

         Variable Tipo de dato  Valores únicos  Valores nulos
0  precio_mensual      float64            4495              0

       precio_mensual
count        67500.00
mean            32.50
std             10.55
min             13.27
25%             24.54
50%             30.56
75%             38.59
max             91.45

       Variable Tipo de dato  Valores únicos  Valores nulos
0  precio_anual      float64           23575              0

       precio_anual
count      67500.00
mean         371.19
std          120.46
min          151.44
25%          280.21
50%          348.92
75%          440.67
max         1044.40

### Conclusiones

El análisis de las variables numéricas permitió identificar dos comportamientos diferenciados dentro del conjunto de datos.

Por un lado, `precio_mensual` corresponde a una variable numérica continua, ya que presenta un elevado número de valores distintos y constituye la variable objetivo del modelo.

Por otro lado, `pet_age_nr`, `capital_vet_total`, `capital_vet_plus` y `capital_rc` son variables cuantitativas discretas. Aunque se almacenan como valores numéricos y podrán utilizarse como tales durante el modelado, únicamente toman un conjunto limitado de valores posibles.

En particular, `pet_age_nr` representa la edad de la mascota en años completos (0 a 9 años), mientras que las variables de capital representan distintos niveles de cobertura del seguro.

No se detectaron valores nulos ni rangos inconsistentes en ninguna de las variables analizadas.

### Decisión

Se conservarán todas las variables numéricas para la fase de modelado.

- `precio_mensual` se utilizará como variable objetivo.
- `pet_age_nr` se mantendrá como variable cuantitativa discreta.
- `capital_vet_total`, `capital_vet_plus` y `capital_rc` se conservarán como variables numéricas discretas, ya que representan distintos niveles de cobertura del seguro.
- `precio_anual` se excluirá del conjunto de predictores por su relación directa con la variable objetivo y el riesgo de **Data Leakage**.

>### Hallazgo
>
>Aunque varias variables están almacenadas como numéricas, el análisis permitió distinguir entre variables continuas y discretas.
>
>Esta diferenciación será tenida en cuenta durante el desarrollo del pipeline de preprocesamiento y en la interpretación posterior del modelo

## 7. Resumen de decisiones de preprocesamiento

### Objetivo

Recopilar las decisiones obtenidas durante el análisis del dataset con el fin de definir una estrategia clara y homogénea para la construcción del pipeline de preprocesamiento del modelo de Machine Learning.

Este resumen servirá como guía para la implementación del Notebook 02, asegurando que todas las transformaciones respondan tanto a la evidencia obtenida en el análisis como a las reglas de negocio identificadas durante el proyecto.

## 7.1 Resumen de decisiones de preprocesamiento

| Variable | Tipo | Decisión | Prioridad | Implementación Notebook 01 |
|-----------|------|----------|:---------:|----------------------------|
| `id` | Identificador | Eliminar | 🟠 Alta | Eliminar antes del entrenamiento. |
| `multisimulation_id` | Identificador | Eliminar | 🟠 Alta | Eliminar antes del entrenamiento. |
| `api_response` | Técnica | Eliminar | 🟠 Alta | Eliminar (100 % valores nulos). |
| `grupo_raza` / `grupo_raza_nombre` | Categórica | Conservar una única representación | 🟠 Alta | Mantener únicamente una de las dos variables. |
| `pet_race_code` / `pet_race_name` | Categórica | Conservar una única representación | 🟠 Alta | Mantener únicamente una de las dos variables. |
| `plan_code` / `plan_name` | Categórica | Conservar una única representación | 🟠 Alta | Mantener únicamente una de las dos variables. |
| `owner_postal_code` / `owner_municipality` | Geográfica | Revisar | 🟡 Media | Validar la representación geográfica antes del modelado. |
| `pet_gender` | Binaria | Conservar | 🟢 Baja | Codificación binaria. |
| `pet_sterilized` | Binaria | Conservar | 🟢 Baja | Codificación binaria. |
| `is_pure_breed` | Booleana | Conservar | 🟢 Baja | Transformar a 0/1. |
| `is_dangerous` | Booleana | Conservar | 🟢 Baja | Transformar a 0/1. |
| `sterilized_when` | Ordinal | Conservar | 🔴 Crítica | Tratamiento especial. Depende de `pet_gender` y `pet_sterilized`. No imputar automáticamente los valores nulos. |
| `fecha_cotizacion` | Temporal | No utilizar inicialmente | 🟡 Media | Excluir como predictor (reevaluar con un histórico mayor). |
| `pet_age_nr` | Numérica discreta | Conservar | 🟡 Media | Evaluar si requiere escalado según el algoritmo utilizado |
| `capital_vet_total` | Numérica discreta | Conservar | 🟡 Media | Mantener como variable numérica discreta. |
| `capital_vet_plus` | Numérica discreta | Conservar | 🟡 Media | Mantener como variable numérica discreta. |
| `capital_rc` | Numérica discreta | Conservar | 🟡 Media | Mantener como variable numérica discreta. |
| `precio_mensual` | Variable objetivo | Conservar | 🔴 Crítica | Definir como variable objetivo (`target`). |
| `precio_anual` | Variable derivada | Excluir | 🔴 Crítica | Eliminar por riesgo de **Data Leakage**. |

## 7.2 Estado de implementación (Notebook 01)

### Objetivo

Registrar el avance de la implementación del pipeline de preprocesamiento definido durante el análisis.

Este apartado permitirá al equipo verificar que todas las decisiones documentadas en el Notebook 01 han sido implementadas correctamente en el Notebook 02, facilitando el seguimiento del trabajo colaborativo y reduciendo el riesgo de omitir transformaciones importantes.

| Transformación | Prioridad | Estado |
|----------------|:---------:|:------:|
| Eliminar variables identificadoras (`id`, `multisimulation_id`) | 🟠 Alta | ☐ Pendiente |
| Eliminar `api_response` | 🟠 Alta | ☐ Pendiente |
| Seleccionar una única representación para raza (`grupo_raza` / `grupo_raza_nombre`) | 🟠 Alta | ☐ Pendiente |
| Seleccionar una única representación para raza específica (`pet_race_code` / `pet_race_name`) | 🟠 Alta | ☐ Pendiente |
| Seleccionar una única representación para plan (`plan_code` / `plan_name`) | 🟠 Alta | ☐ Pendiente |
| Revisar representación geográfica (`owner_postal_code` / `owner_municipality`) | 🟡 Media | ☐ Pendiente |
| Codificar variables binarias | 🟢 Baja | ☐ Pendiente |
| Transformar variables booleanas (`is_pure_breed`, `is_dangerous`) | 🟢 Baja | ☐ Pendiente |
| Aplicar tratamiento especial a `sterilized_when` | 🔴 Crítica | ☐ Pendiente |
| Excluir `fecha_cotizacion` como predictor | 🟡 Media | ☐ Pendiente |
| Revisar escalado de variables numéricas continuas | 🟡 Media | ☐ Pendiente |
| Mantener variables de cobertura como niveles discretos | 🟡 Media | ☐ Pendiente |
| Definir `precio_mensual` como variable objetivo | 🔴 Crítica | ☐ Pendiente |
| Eliminar `precio_anual` para evitar Data Leakage | 🔴 Crítica | ☐ Pendiente |

## 7.3 Leyenda


- ☐ **Pendiente:** transformación aún no implementada.
- 🔄 **En desarrollo:** implementación iniciada.
- ✅ **Implementado:** transformación completada y validada.

#### Prioridades

- 🔴 **Crítica:** imprescindible para garantizar la validez del modelo.
- 🟠 **Alta:** transformación necesaria antes del entrenamiento.
- 🟡 **Media:** recomendable según el algoritmo y la estrategia de modelado.
- 🟢 **Baja:** transformación sencilla con bajo riesgo de implementación.

# 8. Cierre del análisis

El presente notebook documenta el análisis estructural del conjunto de datos y establece las decisiones de preprocesamiento que servirán de base para el desarrollo del pipeline de Machine Learning.

Todas las transformaciones propuestas han sido fundamentadas a partir del análisis exploratorio realizado, las reglas de negocio identificadas y las validaciones efectuadas con el experto de negocio.

La implementación de las transformaciones descritas en este análisis se desarrolla a continuación en este mismo notebook. El resultado final será un conjunto de datos limpio y preparado para la fase de modelado, que se llevará a cabo en el Notebook 02 – Modelado.

# 9. Implementación del preprocesamiento

En esta sección se aplican las decisiones establecidas durante el análisis estructural del conjunto de datos.

El objetivo es construir un dataset limpio y reproducible, preparado para la fase de modelado, preservando la variable objetivo `precio_mensual` y evitando cualquier fuente de Data Leakage.

Las transformaciones se aplicarán sobre una copia del dataset original para conservar intactos los datos de partida.

## 9.1 Carga del conjunto de datos

### Creación de una copia de trabajo

Con el fin de preservar la integridad del conjunto de datos original y garantizar la reproducibilidad del proceso, todas las transformaciones se realizarán sobre una copia del dataset.

De esta forma, `df` conservará los datos originales mientras que `df_clean` contendrá las modificaciones derivadas del preprocesamiento.

In [11]:
import pandas as pd
import numpy as np

# Cargar el dataset original
df = pd.read_csv("../data/matriz_cotizaciones_grupos_original.csv")

# Crear una copia para el preprocesamiento
df_clean = df.copy()

print("=" * 60)
print("Carga del conjunto de datos")
print("=" * 60)
print(f"Dataset original: {df.shape}")
print(f"Copia de trabajo: {df_clean.shape}")

display(df_clean.head())

============================================================
Carga del conjunto de datos
============================================================
Dataset original: (67500, 24)
Copia de trabajo: (67500, 24)

,id,grupo_raza,grupo_raza_nombre,pet_species,pet_race_code,pet_race_name,pet_gender,pet_age_nr,pet_sterilized,sterilized_when,...,plan_code,plan_name,capital_vet_total,capital_vet_plus,capital_rc,precio_mensual,precio_anual,fecha_cotizacion,multisimulation_id,api_response
0,4930,1,Australian Terrier,1,110251,Australian Terrier,M,6,N,NaN,...,3,PET3,1250.0,1000.0,0.0,19.30,220.40,2026-04-11 09:03:45.882914,595360,NaN
1,4931,1,Australian Terrier,1,110251,Australian Terrier,F,7,S,S2,...,3,PET3,1250.0,1000.0,0.0,18.53,211.62,2026-04-11 09:03:54.337379,595362,NaN
2,4932,1,Australian Terrier,1,110251,Australian Terrier,F,7,S,S3,...,3,PET3,1250.0,1000.0,0.0,19.08,217.94,2026-04-11 09:04:01.700459,595364,NaN
3,4933,1,Australian Terrier,1,110251,Australian Terrier,F,7,N,NaN,...,3,PET3,1250.0,1000.0,0.0,19.49,222.58,2026-04-11 09:04:10.074353,595366,NaN
4,4934,1,Australian Terrier,1,110251,Australian Terrier,M,7,S,NaN,...,3,PET3,1250.0,1000.0,0.0,18.86,215.43,2026-04-11 09:04:19.49232,595369,NaN

## 9.2 Eliminación de variables identificadoras y Data Leakage

De acuerdo con las decisiones establecidas durante el análisis previo, se eliminan las variables que no aportan capacidad predictiva o que introducen riesgo de Data Leakage.

En esta primera etapa únicamente se eliminan las variables cuya exclusión fue definida de forma inequívoca durante el análisis.

Las variables que requieren seleccionar una representación única (por ejemplo, código frente a nombre) se tratarán posteriormente.

In [15]:
# Restaurar la copia de trabajo
df_clean = df.copy()

# Variables cuya eliminación fue definida durante el análisis
columnas_eliminar = [
    "id",
    "multisimulation_id",
    "api_response",
    "precio_anual"
]

print("=" * 60)
print("Eliminación de variables identificadoras y Data Leakage")
print("=" * 60)

print(f"Número de columnas antes: {df_clean.shape[1]}")

df_clean.drop(
    columns=columnas_eliminar,
    inplace=True,
    errors="ignore"
)

print(f"Número de columnas después: {df_clean.shape[1]}")

print("\nColumnas eliminadas:")
for columna in columnas_eliminar:
    print(f"• {columna}")

display(df_clean.head())

============================================================
Eliminación de variables identificadoras y Data Leakage
============================================================
Número de columnas antes: 24
Número de columnas después: 20

Columnas eliminadas:
• id
• multisimulation_id
• api_response
• precio_anual

,grupo_raza,grupo_raza_nombre,pet_species,pet_race_code,pet_race_name,pet_gender,pet_age_nr,pet_sterilized,sterilized_when,is_pure_breed,is_dangerous,owner_postal_code,owner_municipality,plan_code,plan_name,capital_vet_total,capital_vet_plus,capital_rc,precio_mensual,fecha_cotizacion
0,1,Australian Terrier,1,110251,Australian Terrier,M,6,N,NaN,t,f,28001,Madrid,3,PET3,1250.0,1000.0,0.0,19.30,2026-04-11 09:03:45.882914
1,1,Australian Terrier,1,110251,Australian Terrier,F,7,S,S2,t,f,28001,Madrid,3,PET3,1250.0,1000.0,0.0,18.53,2026-04-11 09:03:54.337379
2,1,Australian Terrier,1,110251,Australian Terrier,F,7,S,S3,t,f,28001,Madrid,3,PET3,1250.0,1000.0,0.0,19.08,2026-04-11 09:04:01.700459
3,1,Australian Terrier,1,110251,Australian Terrier,F,7,N,NaN,t,f,28001,Madrid,3,PET3,1250.0,1000.0,0.0,19.49,2026-04-11 09:04:10.074353
4,1,Australian Terrier,1,110251,Australian Terrier,M,7,S,NaN,t,f,28001,Madrid,3,PET3,1250.0,1000.0,0.0,18.86,2026-04-11 09:04:19.49232

In [14]:
columnas_restantes = [
    columna
    for columna in columnas_eliminar
    if columna in df_clean.columns
]

if not columnas_restantes:
    print("✅ Todas las columnas están eliminadas correctamente.")
else:
    print("⚠️ Estas columnas siguen presentes:")
    print(columnas_restantes)

✅ Todas las columnas están eliminadas correctamente.

## 9.3 Selección de una única representación de variables redundantes

Durante el análisis previo se comprobó que las siguientes parejas mantienen una correspondencia uno a uno:

- `grupo_raza` y `grupo_raza_nombre`
- `pet_race_code` y `pet_race_name`
- `plan_code` y `plan_name`

Para evitar información redundante, se conserva la representación descriptiva de cada variable, ya que facilita la interpretación posterior de los resultados del modelo.

Por tanto, se eliminan las columnas numéricas `grupo_raza`, `pet_race_code` y `plan_code`.

Las variables geográficas `owner_postal_code` y `owner_municipality` se mantienen inicialmente, de acuerdo con las conclusiones del análisis.

In [16]:
# Columnas redundantes que se eliminarán
columnas_redundantes = [
    "grupo_raza",
    "pet_race_code",
    "plan_code"
]

print("=" * 60)
print("Eliminación de variables redundantes")
print("=" * 60)

print(f"Número de columnas antes: {df_clean.shape[1]}")

df_clean.drop(
    columns=columnas_redundantes,
    inplace=True,
    errors="ignore"
)

print(f"Número de columnas después: {df_clean.shape[1]}")

print("\nColumnas eliminadas:")
for columna in columnas_redundantes:
    print(f"• {columna}")

display(df_clean.head())

============================================================
Eliminación de variables redundantes
============================================================
Número de columnas antes: 20
Número de columnas después: 17

Columnas eliminadas:
• grupo_raza
• pet_race_code
• plan_code

,grupo_raza_nombre,pet_species,pet_race_name,pet_gender,pet_age_nr,pet_sterilized,sterilized_when,is_pure_breed,is_dangerous,owner_postal_code,owner_municipality,plan_name,capital_vet_total,capital_vet_plus,capital_rc,precio_mensual,fecha_cotizacion
0,Australian Terrier,1,Australian Terrier,M,6,N,NaN,t,f,28001,Madrid,PET3,1250.0,1000.0,0.0,19.30,2026-04-11 09:03:45.882914
1,Australian Terrier,1,Australian Terrier,F,7,S,S2,t,f,28001,Madrid,PET3,1250.0,1000.0,0.0,18.53,2026-04-11 09:03:54.337379
2,Australian Terrier,1,Australian Terrier,F,7,S,S3,t,f,28001,Madrid,PET3,1250.0,1000.0,0.0,19.08,2026-04-11 09:04:01.700459
3,Australian Terrier,1,Australian Terrier,F,7,N,NaN,t,f,28001,Madrid,PET3,1250.0,1000.0,0.0,19.49,2026-04-11 09:04:10.074353
4,Australian Terrier,1,Australian Terrier,M,7,S,NaN,t,f,28001,Madrid,PET3,1250.0,1000.0,0.0,18.86,2026-04-11 09:04:19.49232

In [17]:
columnas_redundantes_restantes = []

for columna in columnas_redundantes:
    if columna in df_clean.columns:
        columnas_redundantes_restantes.append(columna)

if len(columnas_redundantes_restantes) == 0:
    print("✅ Las variables redundantes fueron eliminadas correctamente.")
else:
    print("⚠️ Estas variables todavía están presentes:")
    print(columnas_redundantes_restantes)

✅ Las variables redundantes fueron eliminadas correctamente.

## 9.4 Tratamiento de valores nulos

El análisis previo identificó valores nulos únicamente en las variables `sterilized_when` y `owner_municipality`.

En `sterilized_when`, los valores nulos no representan pérdida de información. El análisis conjunto con `pet_gender` y `pet_sterilized` demostró que corresponden a situaciones en las que el momento de la esterilización no aplica. Por tanto, se transformarán explícitamente en la categoría `"No aplica"`, preservando la lógica del negocio.

En `owner_municipality` se identificaron únicamente 40 valores nulos. Dado que no existe evidencia suficiente para asignar un municipio concreto y no se desea eliminar registros, estos valores se transformarán en la categoría `"Municipio no informado"`.

No se utilizarán técnicas estadísticas de imputación para ninguna de las dos variables.
Código

In [20]:
# Comprobación de valores nulos
nulos = df_clean.isna().sum()

display(nulos[nulos > 0])

sterilized_when       40500
owner_municipality       40
dtype: int64

In [21]:
print("=" * 60)
print("Tratamiento de valores nulos")
print("=" * 60)

print("Valores nulos antes del tratamiento:")
display(df_clean[["sterilized_when", "owner_municipality"]].isna().sum())

df_clean["sterilized_when"] = df_clean["sterilized_when"].fillna("No aplica")

df_clean["owner_municipality"] = (
    df_clean["owner_municipality"]
    .fillna("Municipio no informado")
)

print("\nValores nulos después del tratamiento:")
display(df_clean[["sterilized_when", "owner_municipality"]].isna().sum())

============================================================
Tratamiento de valores nulos
============================================================
Valores nulos antes del tratamiento:

sterilized_when       40500
owner_municipality       40
dtype: int64

Valores nulos después del tratamiento:

sterilized_when       0
owner_municipality    0
dtype: int64

In [22]:
if df_clean[["sterilized_when", "owner_municipality"]].isna().sum().sum() == 0:
    print("✅ Los valores nulos fueron tratados correctamente.")
else:
    print("⚠️ Todavía quedan valores nulos por revisar.")

✅ Los valores nulos fueron tratados correctamente.

## 9.5 Transformación de variables binarias

Las variables `is_pure_breed` e `is_dangerous` contienen únicamente dos categorías (`t` y `f`).

Para facilitar el entrenamiento de los modelos supervisados, ambas variables se transforman a una representación numérica:

- `t` → 1
- `f` → 0

Esta transformación mantiene la información original y evita que el algoritmo tenga que interpretar valores de texto.

In [23]:
print("=" * 60)
print("Transformación de variables binarias")
print("=" * 60)

# Conversión de variables binarias
df_clean["is_pure_breed"] = df_clean["is_pure_breed"].map({
    "t": 1,
    "f": 0
})

df_clean["is_dangerous"] = df_clean["is_dangerous"].map({
    "t": 1,
    "f": 0
})

print("Conversión realizada correctamente.")

============================================================
Transformación de variables binarias
============================================================
Conversión realizada correctamente.

In [26]:
print("Valores únicos después de la transformación:\n")

print("is_pure_breed:")
print(sorted(df_clean["is_pure_breed"].unique()))

print("\nis_dangerous:")
print(sorted(df_clean["is_dangerous"].unique()))

print(f"\nDimensiones actuales del dataset: {df_clean.shape}")

Valores únicos después de la transformación:

is_pure_breed:
[np.int64(0), np.int64(1)]

is_dangerous:
[np.int64(0), np.int64(1)]

Dimensiones actuales del dataset: (67500, 17)

## 9.6 Codificación de variables categóricas de baja cardinalidad

Las variables categóricas con un número reducido de categorías se transforman mediante One-Hot Encoding utilizando la función `pd.get_dummies()` de pandas.

Esta técnica crea una nueva columna binaria para cada categoría, evitando introducir un orden artificial entre ellas y permitiendo que los algoritmos de Machine Learning trabajen correctamente con variables categóricas nominales.

Las variables transformadas son:

- `pet_species`
- `pet_gender`
- `pet_sterilized`
- `sterilized_when`
- `plan_name`

Las variables con alta cardinalidad se tratarán en un apartado posterior.

In [29]:
print("=" * 60)
print("Codificación de variables categóricas de baja cardinalidad")
print("=" * 60)

variables_baja_cardinalidad = [
    "pet_species",
    "pet_gender",
    "pet_sterilized",
    "sterilized_when",
    "plan_name"
]

print("Variables a transformar:")
for variable in variables_baja_cardinalidad:
    print(f"• {variable}")

df_clean = pd.get_dummies(
    df_clean,
    columns=variables_baja_cardinalidad,
    dtype=int
)

# Buena práctica: eliminar espacios en los nombres de las columnas
df_clean.columns = df_clean.columns.str.replace(" ", "_")

print("\nCodificación realizada correctamente.")

============================================================
Codificación de variables categóricas de baja cardinalidad
============================================================
Variables a transformar:
• pet_species
• pet_gender
• pet_sterilized
• sterilized_when
• plan_name

KeyError: "None of [Index(['pet_species', 'pet_gender', 'pet_sterilized', 'sterilized_when',\n       'plan_name'],\n      dtype='str')] are in the [columns]"

In [30]:
columnas_antes = set([
    "grupo_raza_nombre",
    "pet_species",
    "pet_race_name",
    "pet_gender",
    "pet_age_nr",
    "pet_sterilized",
    "sterilized_when",
    "is_pure_breed",
    "is_dangerous",
    "owner_postal_code",
    "owner_municipality",
    "plan_name",
    "capital_vet_total",
    "capital_vet_plus",
    "capital_rc",
    "precio_mensual",
    "fecha_cotizacion"
])

columnas_despues = set(df_clean.columns)

columnas_nuevas = sorted(columnas_despues - columnas_antes)

print("Nuevas columnas creadas:\n")

for columna in columnas_nuevas:
    print(columna)

print(f"\nDimensiones actuales del dataset: {df_clean.shape}")

Nuevas columnas creadas:

pet_gender_F
pet_gender_M
pet_species_1
pet_species_2
pet_sterilized_N
pet_sterilized_S
plan_name_PET VITAL
plan_name_PET3
sterilized_when_No aplica
sterilized_when_S2
sterilized_when_S3

Dimensiones actuales del dataset: (67500, 23)

### 9.7 Codificación de las variables categóricas restantes

Tras revisar las variables categóricas restantes durante el análisis exploratorio, se comprobó que presentan una cardinalidad asumible para este conjunto de datos.

Por este motivo, se aplicará **One-Hot Encoding** mediante `pd.get_dummies()`, permitiendo que los algoritmos de Machine Learning trabajen correctamente con estas variables.

Las variables transformadas son:

- `grupo_raza_nombre`
- `pet_race_name`
- `owner_postal_code`
- `owner_municipality`

El código postal se trata como una variable categórica, ya que representa una ubicación geográfica y no una magnitud numérica.

In [35]:
print("=" * 60)
print("Codificación de las variables categóricas restantes")
print("=" * 60)

variables_restantes = [
    "grupo_raza_nombre",
    "pet_race_name",
    "owner_postal_code",
    "owner_municipality"
]

print("Variables a transformar:")

for variable in variables_restantes:
    print(f"• {variable}")

df_clean = pd.get_dummies(
    df_clean,
    columns=variables_restantes,
    dtype=int
)

print("\nCodificación realizada correctamente.")

============================================================
Codificación de las variables categóricas restantes
============================================================
Variables a transformar:
• grupo_raza_nombre
• pet_race_name
• owner_postal_code
• owner_municipality

Codificación realizada correctamente.

In [37]:
columnas_antes = {
    "grupo_raza_nombre",
    "pet_race_name",
    "owner_postal_code",
    "owner_municipality",
    "pet_age_nr",
    "is_pure_breed",
    "is_dangerous",
    "capital_vet_total",
    "capital_vet_plus",
    "capital_rc",
    "precio_mensual",
    "fecha_cotizacion",
    "pet_species_1",
    "pet_species_2",
    "pet_gender_F",
    "pet_gender_M",
    "pet_sterilized_N",
    "pet_sterilized_S",
    "sterilized_when_No aplica",
    "sterilized_when_S2",
    "sterilized_when_S3",
    "plan_name_PET VITAL",
    "plan_name_PET3"
}

columnas_despues = set(df_clean.columns)

columnas_nuevas = sorted(columnas_despues - columnas_antes)

print("Nuevas columnas creadas:\n")

for columna in columnas_nuevas:
    print(columna)

print(f"\nCantidad de columnas nuevas creadas: {len(columnas_nuevas)}")
print(f"Dimensiones actuales del dataset: {df_clean.shape}")

Nuevas columnas creadas:

grupo_raza_nombre_Abisinio
grupo_raza_nombre_Affenpinscher
grupo_raza_nombre_Airedale Terrier
grupo_raza_nombre_Akita Americano (G Perro Japones)
grupo_raza_nombre_Akita Inu
grupo_raza_nombre_American Staffordshire Terrier
grupo_raza_nombre_Anglo-Francais De Petite Venerie
grupo_raza_nombre_Australian Terrier
grupo_raza_nombre_Balinés
grupo_raza_nombre_Beagle
grupo_raza_nombre_Biewer Terrier
grupo_raza_nombre_Boxer
grupo_raza_nombre_Bull Terrier
grupo_raza_nombre_Bullmastiff
grupo_raza_nombre_Caniche Enano (Poodle Mini)
grupo_raza_nombre_Caniche Miniatura (Poodle Toy)
grupo_raza_nombre_Exotic
grupo_raza_nombre_Gato Común/European Shorthair Cat
grupo_raza_nombre_Mestizo Gigante (Más de 45 Kg)
grupo_raza_nombre_Mestizo Grande (Entre 21 y 45 Kg)
grupo_raza_nombre_Mestizo Mediano (Entre 11 y 20 Kg)
grupo_raza_nombre_Mestizo Miniatura (Menos de 5 Kg)
grupo_raza_nombre_Mestizo Pequeño (Entre 5 y 10 Kg)
grupo_raza_nombre_Shar Pei
grupo_raza_nombre_Spaniel Continental Enano De Compañía (Papillon / Phaléne)
owner_municipality_Albacete
owner_municipality_Alcalá del Júcar
owner_municipality_Madrid
owner_municipality_Majadahonda
owner_municipality_Municipio no informado
owner_municipality_Zaragoza
owner_postal_code_02124
owner_postal_code_02210
owner_postal_code_28001
owner_postal_code_28220
owner_postal_code_50001
pet_race_name_Abisinio
pet_race_name_Affenpinscher
pet_race_name_Airedale Terrier
pet_race_name_Akita Americano (G Perro Japones)
pet_race_name_Akita Inu
pet_race_name_American Staffordshire Terrier
pet_race_name_Anglo-Francais De Petite Venerie
pet_race_name_Australian Terrier
pet_race_name_Balinés
pet_race_name_Beagle
pet_race_name_Biewer Terrier
pet_race_name_Boxer
pet_race_name_Bull Terrier
pet_race_name_Bullmastiff
pet_race_name_Caniche Enano (Poodle Mini)
pet_race_name_Caniche Miniatura (Poodle Toy)
pet_race_name_Exotic
pet_race_name_Gato Común/European Shorthair Cat
pet_race_name_Mestizo Gigante (Más de 45 Kg)
pet_race_name_Mestizo Grande (Entre 21 y 45 Kg)
pet_race_name_Mestizo Mediano (Entre 11 y 20 Kg)
pet_race_name_Mestizo Miniatura (Menos de 5 Kg)
pet_race_name_Mestizo Pequeño (Entre 5 y 10 Kg)
pet_race_name_Shar Pei
pet_race_name_Spaniel Continental Enano De Compañía (Papillon / Phaléne)

Cantidad de columnas nuevas creadas: 61
Dimensiones actuales del dataset: (67500, 80)

### 9.8 Exclusión de la variable temporal

Durante el análisis exploratorio se evaluó la variable `fecha_cotizacion`, observando que el conjunto de datos únicamente recoge cotizaciones realizadas entre el 11 y el 21 de abril de 2026.

Aunque existen pequeñas variaciones diarias en el número de cotizaciones y en el precio medio, el periodo temporal analizado es demasiado reducido para capturar patrones estacionales o tendencias representativas.

Por este motivo, se decide excluir esta variable del conjunto de entrenamiento. En caso de disponer de un histórico más amplio, podría reconsiderarse su utilización mediante ingeniería de características temporales.

In [38]:
print("=" * 60)
print("Eliminación de la variable temporal")
print("=" * 60)

df_clean = df_clean.drop(columns="fecha_cotizacion")

print("Variable 'fecha_cotizacion' eliminada correctamente.")

============================================================
Eliminación de la variable temporal
============================================================
Variable 'fecha_cotizacion' eliminada correctamente.

In [39]:
print("¿Existe 'fecha_cotizacion' en el dataset?")

if "fecha_cotizacion" in df_clean.columns:
    print("La variable sigue presente.")
else:
    print("La variable ha sido eliminada correctamente.")

print(f"\nDimensiones finales del dataset: {df_clean.shape}")

¿Existe 'fecha_cotizacion' en el dataset?
La variable ha sido eliminada correctamente.

Dimensiones finales del dataset: (67500, 79)

### 9.9 Validación final del conjunto de datos

Tras completar todas las etapas del preprocesamiento, se realiza una validación final del conjunto de datos para comprobar que:

- No existen valores nulos.
- No existen registros duplicados.
- Todas las variables presentan un tipo de dato adecuado para el entrenamiento.
- El conjunto de datos mantiene las dimensiones esperadas.

Esta comprobación garantiza que el dataset está preparado para la fase de entrenamiento y evaluación de modelos supervisados.

In [40]:
print("=" * 60)
print("Validación final del dataset")
print("=" * 60)

print(f"Filas: {df_clean.shape[0]}")
print(f"Columnas: {df_clean.shape[1]}")

print(f"\nValores nulos: {df_clean.isna().sum().sum()}")

print(f"Registros duplicados: {df_clean.duplicated().sum()}")

print("\nTipos de datos:")

print(df_clean.dtypes.value_counts())

============================================================
Validación final del dataset
============================================================
Filas: 67500
Columnas: 79

Valores nulos: 0
Registros duplicados: 0

Tipos de datos:
int64      75
float64     4
Name: count, dtype: int64

In [41]:
if (
    df_clean.isna().sum().sum() == 0
    and df_clean.duplicated().sum() == 0
):
    print("\nDataset preparado correctamente para el modelado.")
else:
    print("\nRevisar el dataset antes del entrenamiento.")

Dataset preparado correctamente para el modelado.

## 10. Exportación del conjunto de datos preprocesado

Una vez completadas todas las etapas de limpieza y transformación, el conjunto de datos preprocesado se almacena para su utilización en las fases posteriores del proyecto.

El archivo generado servirá como entrada para el notebook de modelado, garantizando que todos los experimentos se realicen sobre el mismo conjunto de datos preparado.

In [42]:
from pathlib import Path

ruta_salida = Path("../data/matriz_cotizaciones_grupos_preprocesada.csv")

df_clean.to_csv(
    ruta_salida,
    index=False
)

print("=" * 60)
print("Dataset exportado correctamente")
print("=" * 60)
print(f"Ruta: {ruta_salida}")
print(f"Dimensiones: {df_clean.shape}")

============================================================
Dataset exportado correctamente
============================================================
Ruta: ..\data\matriz_cotizaciones_grupos_preprocesada.csv
Dimensiones: (67500, 79)

**Nota:** El archivo `matriz_cotizaciones_grupos_preprocesada.csv` se genera automáticamente al ejecutar este notebook. No se incluye en el repositorio porque la carpeta `src/data/` está excluida mediante `.gitignore`, siguiendo las restricciones de confidencialidad del proyecto. Cada miembro del equipo puede reproducir este archivo ejecutando el presente notebook a partir del conjunto de datos original.